language: node_js

node_js:
  - "7"
  - "6"
  - "4"

env:
  - TS="typescript@latest"
  - TS="typescript@next"
  - TS="typescript@rc"
  - TS="typescript@1"

before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
  - npm install grunt-cli -g
  - npm install grunt $TS
