language: node_js

node_js:
  - "6"
  - "4"

env:
  - TS="typescript@latest"
  - TS="typescript@next"
  - TS="typescript@rc"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install grunt-cli -g
  - npm install grunt $TS
